version: '3.4'

services:
  redis:
   container_name: redis
   hostname: redis
   image: redis
   environment:
   - ALLOW_EMPTY_PASSWORD=yes
   command: redis-server ./redis.conf
   volumes:
   - ./redis.conf:/home/guba/redis.conf
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - "8081:8081"
  
  psql:
    image: postgres
    container_name: psql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: Rapaport
  elasticsearch:
    image: elasticsearch:7.16.2
    container_name: elastic
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - docker_elk
  
  kibana:
    image: kibana:7.16.2
    ports:
      - "5601:5601"
    links:
      - elasticsearch
    networks:
      - docker_elk

networks:
  docker_elk:
    driver: bridge
    